.PHONY: zad1 zad2 zad3 zad4 zad5 zad6 all

all: zad1 zad2 zad3 zad4 zad5 zad6

zad1:
	@echo "zad1"
	cd zad1 && gnatmake philosophers.adb && ./philosophers 5 10

zad2:
	@echo "zad2"
	cd zad2 && go run philosophers.go 5 10

zad3:
	@echo "zad3"
	cd zad3 && javac Philosophers.java && java Philosophers 5 10

zad4:
	@echo "zad4"
	cd zad4 && gnatmake star_messaging.adb && ./star_messaging 5 10

zad5:
	@echo "zad5"
	cd zad5 && go run star_messaging.go 5 10

zad6:
	@echo "zad6"
	cd zad6 && javac StarMessaging.java && java StarMessaging 5 10