.PHONY: zad1 zad2 zad3 all

all: zad1 zad2 zad3

zad1:
	@echo "zad1"
	cd zad1 && g++ ring.cpp -o ring && ./ring

zad2:
	@echo "zad2"
	cd zad2 && gnatmake main.adb && ./main

zad3:
	@echo "zad3"
	cd zad3 && rustc main.rs && ./main