.PHONY: zad1 zad2 zad3 zad4 zad5 zad6 all

all: zad1 zad2 zad3 zad4 zad5 zad6

zad1:
	@echo "zad1"
	cd zad1 && g++ rsa.cpp -o rsa && ./rsa

zad2:
	@echo "zad2"
	cd zad2 && gnatmake main.adb && ./main

zad3:
	@echo "zad3"
	cd zad3 && rustc main.rs && ./main

zad4:
	@echo "zad4"
	cd zad4 && g++ main.cpp -o main && ./main

zad5:
	@echo "zad5"
	cd zad5 && gnatmake main.adb && ./main

zad6:
	@echo "zad6"
	cd zad6 && cd dh_rust && cargo run