(defun egcd (a b)
  (if (= b 0)
      (list 1 0 a)
      (let* ((rec (egcd b (mod a b)))
             (x1 (first rec))
             (y1 (second rec))
             (g  (third rec))
             (x y1)
             (y (- x1 (* (floor a b) y1))))
        (list x y g))))

(let* ((args (cdr sb-ext:*posix-argv*))
       (a (parse-integer (first args)))
       (b (parse-integer (second args))))
  (format t "~a~%" (egcd a b)))